services:
  fumimi:
    image: fumimi-discord:latest
    build: .
    restart: unless-stopped

    environment:
      RUBY_DEBUG_OPEN: "true"
      RUBY_DEBUG_NONSTOP: "true"

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/up"]

    volumes:
      - .:/app
