services:
  fumimi:
    image: fumimi-discord:latest
    build: .
    restart: unless-stopped

    environment:
      RUBY_DEBUG_OPEN: "true"
      RUBY_DEBUG_NONSTOP: "true"

    volumes:
      - .:/app
