# Run the tests after the Docker image is successfully built.

name: Test

# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#permissions
permissions: read-all

on:
  # https://docs.github.com/en/actions/reference/events-that-trigger-workflows#workflow_run
  workflow_run:
    workflows: ["Docker Build"]
    types: [completed]

  workflow_dispatch:
    inputs:
      debug_enabled:
        description: "Run the workflow with remote debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)"
        required: false
        default: false

defaults:
 run:
   working-directory: /root

jobs:
  test:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    # Don't run the test suite multiple times for the same commit.
    concurrency: "test-${{ github.sha }}"

    runs-on: ubuntu-latest

    container:
      image: ghcr.io/danbooru/fumimi-discord:${{ github.sha }}
      options: --user root

    steps:
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      timeout-minutes: 20
      if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled }}
      with:
        limit-access-to-actor: true
        sudo: false

    - name: Run tests
      run: |
        bundle exec rake test TESTOPTS="-v"
